### ISSUE TITLE
CI should build a binary version of LIMA based on /pypa/manylinux

### ISSUE THREAD

**Issue by kleag** [aymara/lima#123]
**Is your feature request related to a problem? Please describe.**
The current LIMA python binding is using a docker container to run LIMA or a local install. But docker is not available for all users and local install can necessitate root access or complex building knowledge. The lima python binding should be installable and runnable with pip only.

**Describe the solution you'd like**
Add a Continuous Integration build based on the pypa/manylinux infrastructure to be able to build a generally usable python wheel.

https://github.com/pypa/manylinux

**Comment by kleag** [comment]
This could be a good useful tool to help building the wheel: 
https://www.riverbankcomputing.com/software/pyqt-builder/

**Comment by kleag** [comment]
To include all .so in final wheel: https://github.com/pypa/auditwheel

**Comment by kleag** [comment]
We now have a docker hub image of lima based on manylinux_2_24: https://hub.docker.com/repository/docker/aymara/lima-manylinux_2_24 (itself based on an image with tensorflow-for-lima: https://hub.docker.com/repository/docker/aymara/tensorflow_for_lima_1_9-manylinux_2_24)

Tasks remaining:

- build a python binding of lima libs 
- link the binding with existing python-lima currently running a lima docker container in the background).

**Comment by kleag** [comment]
To install PySide2/shiboken2 on my KDE Neon. I had to install the module corresponding to my Qt distribution with pip and then complete with the following wheel directly from qt.io:
```bash
wget https://download.qt.io/official_releases/QtForPython/shiboken2-generator/shiboken2_generator-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl
```
Otherwise, the configure of the example failed with: 
```bash
(lima) gael@brezhoneg2:~/Logiciels/Example_Qt_and_Shiboken2/build$ cmake ..Python3_SITELIB: /usr/lib/python3/dist-packages
Unable to locate shiboken2-generator. Did you forget to activate your virtualenv? Or perhaps you forgot to build / install PySide2 into your currently active Python environment?
CMake Error at CMakeLists.txt:72 (message):
  Error: Calling pyside2_config.py --shiboken2-generator-path returned no
  output.
Call Stack (most recent call first):
  CMakeLists.txt:80 (pyside2_config)
```

**Comment by kleag** [comment]
This example worked with some changes 
https://github.com/basysKom/Example_Qt_and_Shiboken2

I made some changes to the CMakeLists.txt, very specific to my installation:
[CMakeLists.txt](https://github.com/aymara/lima/files/7468799/CMakeLists.txt)

```bash
$ mkvirtualenv -p /usr/bin/python3.7 pyside
$ pip install PySide2
$ wget https://download.qt.io/official_releases/QtForPython/shiboken2-generator/shiboken2_generator-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl
$ pip install shiboken2_generator-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl 
$ cd build/
$ export LD_LIBRARY_PATH=/home/gael/.virtualenvs/pyside/lib/python3.7/site-packages/shiboken2:/home/gael/.virtualenvs/pyside/lib/python3.7/site-packages/PySide2/Qt/lib
$ cmake ..
$ make
$ make install
$ cd ..
$ python main.py 
```

**Comment by kleag** [comment]
I was able to build locally a shiboken2/pyside2-based LIMA binding using scikit-build (https://scikit-build.readthedocs.io/en/latest/). I'm now trying to build it in a manylinux_2_24 based docker container. Unfortunately, building pyside inside the container fails at:
```
RUN python3.8 setup.py bdist_wheel
```
With:
```
Inserting path '/opt/_internal/cpython-3.8.12/bin' to environment
error: Failed to locate the Python library with /opt/_internal/cpython-3.8.12/lib/x86_64-linux-gnu/libpython3.8.so, /opt/_internal/cpython-3.8.12/lib/x86_64-linux-gnu/libpython3.8.so.1, /opt/_internal/cpython-3.8.12/lib/x86_64-linux-gnu/libpython3.8.so.1.0, /opt/_internal/cpython-3.8.12/lib/x86_64-linux-gnu/libpython3.8.a
Traceback (most recent call last):
  File "setup.py", line 296, in <module>
    setup_runner.run_setup()
  File "/pyside-setup/build_scripts/setup_runner.py", line 168, in run_setup
    raise RuntimeError(msg)
RuntimeError: 
setup.py invocation failed with exit code: 1.


setup.py invocation was: /usr/local/bin/python3.8 setup.py install --cmake=/usr/local/bin/cmake --build-type=all --internal-build-type=shiboken2
```

It seems that one cannot have a libpython inside a wheel and/or the manylinux container, by design (https://github.com/pypa/manylinux/issues/255). Because python extension should not link against libpython.

I will open issues at Qt, scikit-build and manylinux to try to find who is responsible and what are the solutions.

**Comment by kleag** [comment]
The issues have been opened two weeks ago. See above for the links to those on github and [here](https://bugreports.qt.io/browse/PYSIDE-1748) for the one on Qt.
None have got any answer currently (let's hope it is related to holidays…).

**Comment by kleag** [comment]
@mayeut found a long term solution and a short term workaround for this problem which originates from PySide in fact:
https://github.com/pypa/manylinux/issues/1243
The lima wheel builds in manylinux_2_24.
I can now continue the integration by integrating all dependent libraries inside the wheel.

**Comment by kleag** [comment]
The current lima-python now works without installing docker or packages.
TODO:
* correct the problem of LD_LIBRARY_PATH needing to be set to find libraries in the wheel

**Comment by kleag** [comment]
The current lima_manylinux_2_24 image is in fact wrong because it was built with builtin Qt libs which are at 5.7 while the PySide2 used in the lima-python_manylinux_2_24 built from it uses Qt 5.15 which were installed from online binaries which are not manylinux compatible.
So, lima_manylinux_2_24 will have to be rebuildt with an added step of downloading Qt 5.15 sources and compiling them offline, which is complicated with current Qt installer…

**Comment by kleag** [comment]
This blog post and the links it contains should help with multi stage docker and a qt5 build script.

**Comment by kleag** [comment]
Image corrected with correct Qt built from sources as well as a tensorflow-for-lima dedicated.
TODO:
- correct plugins system. Currently, the pip installed wheel in my local computer cannot load named entites plugin libraries (like lima-lp-se-number) 
- integrate config files and resources into the wheel and allow the python binding to find them.

**Comment by kleag** [comment]
Some more notes, maybe redundant:


# To collect external shared libraries dependencies and include them in a wheel

https://github.com/pypa/auditwheel

# pybind11 based bindings
https://github.com/yssource/pybind11-qt-foo


https://scikit-build.readthedocs.io/en/latest/
https://discuss.python.org/t/notes-on-binary-wheel-packaging-for-c-library-wrappers/2609
https://github.com/riddell-stan/poetry-install-shared-lib-demo

Important information concerning the handling of dependencies between manylinux (debian image is docker 9), which only has GCC 6
while C++17 requires at least GCC 8, and glibc versions:
http://catherineh.github.io/programming/2021/11/16/python-binary-distributions-whls-with-c17-cmake-auditwheel-and-manylinux
Based on: https://martinopilia.com/posts/2018/09/15/building-python-extension.html

General information on python wheels
https://docs.python.org/3.7/distutils/setupscript.html
https://setuptools.pypa.io/en/latest/

A project that includes all what we seem to need
https://github.com/palaimon/fastfm2

**Comment by kleag** [comment]
It works.
